export {HomePage} from './homePage';
export {LoginPage} from './loginPage';
export {MyInfoPage} from './myInfoPage';
export {DirectoryPage} from './directoryPage';
export {PerformancePage} from './performancePage';
export {TimePage} from './timePage';
export {PIMPage} from './pimPage';
export { BuzzPage } from './buzzPage';
export { MaintenancePage } from './maintenancePage';
export { AdminPage } from './adminPage';
export { Dashboard } from './dashboardPage';
export { Leave } from './leavePage';
export { Recruitment } from './recruitmentPage';